# Enable AOF persistence
appendonly yes
appendfsync everysec

# Snapshot saves (RDB) — optional
save 900 1
save 300 10
save 60 10000

# Set Redis working dir
dir /data

# Memory usage limit
maxmemory 100mb
maxmemory-policy allkeys-lru

# Security
# Disabled since we use ACL authentication
protected-mode no

# aclfile saved safely to redis volume after redis reload and ACL save
aclfile /data/users.acl

# ACL Configuration
# Default user enabled temporarily for setup
# Will be disabled by entrypoint script after creating quickbite username
